"""Dynamic terrain suite/layout definitions.

Layouts are deliberately data-only: the manager turns these obstacle specs into
Isaac Gym box actors while keeping static heightfields and triangle meshes
unchanged.
"""


def hurdle(
    name, x, y, z, axis, amp, freq, phase, length=1.0, thickness=0.08, height=0.35
):
    return {
        "name": name,
        "type": "moving_hurdle",
        "actor_count": 1,
        "base_position": [x, y, z],
        "size": [length, thickness, height],
        "motion_axis": axis,
        "amplitude_range": amp,
        "frequency_range": freq,
        "phase_range": phase,
    }


def step(name, x, y, z, amp, freq, phase, length=0.6, width=1.0, height=0.18):
    return {
        "name": name,
        "type": "changing_step_height",
        "actor_count": 1,
        "base_position": [x, y, z],
        "size": [length, width, height],
        "motion_axis": "z",
        "amplitude_range": amp,
        "frequency_range": freq,
        "phase_range": phase,
        "step_height": height,
    }


def gap(
    name,
    x,
    y,
    z,
    axis,
    amp,
    freq,
    phase,
    separation=1.20,
    length=0.55,
    width=1.15,
    height=0.10,
):
    return {
        "name": name,
        "type": "shifting_gap",
        "actor_count": 2,
        "base_position": [x, y, z],
        "size": [length, width, height],
        "motion_axis": axis,
        "edge_separation": separation,
        "amplitude_range": amp,
        "frequency_range": freq,
        "phase_range": phase,
    }


def ramp(
    name,
    x,
    y,
    z,
    amp,
    freq,
    phase,
    base_pitch=0.15,
    length=1.35,
    width=1.15,
    thickness=0.045,
):
    return {
        "name": name,
        "type": "time_varying_ramp",
        "actor_count": 1,
        "base_position": [x, y, z],
        "size": [length, width, thickness],
        "motion_axis": "pitch",
        "base_pitch": base_pitch,
        "amplitude_range": amp,
        "frequency_range": freq,
        "phase_range": phase,
    }


def course_layout(
    name, difficulty, runup_length, runout_length, corridor_half_width, obstacles
):
    return {
        "name": name,
        "difficulty": difficulty,
        "runup_length": runup_length,
        "runout_length": runout_length,
        "corridor_half_width": corridor_half_width,
        "obstacles": obstacles,
    }


DYNAMIC_TERRAIN_SUITES = {
    "pure_hurdle": [
        course_layout(
            "single_barrier_course",
            "easy",
            1.0,
            1.1,
            0.65,
            [
                hurdle(
                    "easy_hurdle_barrier",
                    1.55,
                    0.0,
                    0.30,
                    "y",
                    [0.06, 0.16],
                    [0.08, 0.22],
                    [0.0, 6.28318530718],
                    length=0.10,
                    thickness=1.15,
                    height=0.30,
                ),
            ],
        ),
        course_layout(
            "double_barrier_course",
            "medium",
            1.0,
            1.1,
            0.65,
            [
                hurdle(
                    "medium_hurdle_entry",
                    1.45,
                    0.0,
                    0.31,
                    "y",
                    [0.07, 0.18],
                    [0.08, 0.24],
                    [0.0, 3.14159265359],
                    length=0.10,
                    thickness=1.15,
                    height=0.31,
                ),
                hurdle(
                    "medium_hurdle_exit",
                    2.35,
                    0.0,
                    0.36,
                    "y",
                    [0.08, 0.20],
                    [0.09, 0.26],
                    [3.14159265359, 6.28318530718],
                    length=0.10,
                    thickness=1.15,
                    height=0.36,
                ),
            ],
        ),
        course_layout(
            "staggered_barrier_course",
            "hard",
            1.0,
            1.15,
            0.70,
            [
                hurdle(
                    "hard_hurdle_left",
                    1.45,
                    -0.22,
                    0.32,
                    "y",
                    [0.06, 0.17],
                    [0.08, 0.24],
                    [0.0, 3.14159265359],
                    length=0.10,
                    thickness=0.85,
                    height=0.32,
                ),
                hurdle(
                    "hard_hurdle_right",
                    2.20,
                    0.22,
                    0.38,
                    "y",
                    [0.08, 0.22],
                    [0.10, 0.28],
                    [3.14159265359, 6.28318530718],
                    length=0.10,
                    thickness=0.85,
                    height=0.38,
                ),
                hurdle(
                    "hard_hurdle_center",
                    2.95,
                    0.0,
                    0.34,
                    "y",
                    [0.05, 0.16],
                    [0.08, 0.22],
                    [1.57079632679, 4.71238898038],
                    length=0.10,
                    thickness=1.05,
                    height=0.34,
                ),
            ],
        ),
        course_layout(
            "multi_hurdle_short_course",
            "hardest",
            0.9,
            1.2,
            0.72,
            [
                hurdle(
                    "multi_hurdle_1",
                    1.25,
                    0.0,
                    0.30,
                    "y",
                    [0.05, 0.16],
                    [0.08, 0.24],
                    [0.0, 3.14159265359],
                    length=0.10,
                    thickness=1.05,
                    height=0.30,
                ),
                hurdle(
                    "multi_hurdle_2",
                    1.95,
                    -0.20,
                    0.34,
                    "y",
                    [0.06, 0.18],
                    [0.09, 0.26],
                    [1.57079632679, 4.71238898038],
                    length=0.10,
                    thickness=0.82,
                    height=0.34,
                ),
                hurdle(
                    "multi_hurdle_3",
                    2.65,
                    0.22,
                    0.38,
                    "y",
                    [0.07, 0.20],
                    [0.10, 0.30],
                    [3.14159265359, 6.28318530718],
                    length=0.10,
                    thickness=0.82,
                    height=0.38,
                ),
                hurdle(
                    "multi_hurdle_4",
                    3.35,
                    0.0,
                    0.35,
                    "y",
                    [0.05, 0.16],
                    [0.08, 0.24],
                    [0.0, 6.28318530718],
                    length=0.10,
                    thickness=1.10,
                    height=0.35,
                ),
            ],
        ),
    ],
    "pure_step": [
        course_layout(
            "two_level_step",
            "easy",
            1.0,
            1.2,
            0.65,
            [
                step(
                    "two_level_step_lower",
                    1.75,
                    0.0,
                    0.12,
                    [0.02, 0.08],
                    [0.05, 0.20],
                    [0.0, 3.14159265359],
                    length=0.62,
                    width=1.15,
                    height=0.12,
                ),
                step(
                    "two_level_step_upper",
                    2.45,
                    0.0,
                    0.24,
                    [0.02, 0.09],
                    [0.05, 0.20],
                    [3.14159265359, 6.28318530718],
                    length=0.72,
                    width=1.15,
                    height=0.24,
                ),
            ],
        ),
        course_layout(
            "three_step_staircase",
            "medium",
            0.95,
            1.2,
            0.65,
            [
                step(
                    "stair_step_1",
                    1.55,
                    0.0,
                    0.10,
                    [0.015, 0.06],
                    [0.05, 0.18],
                    [0.0, 2.09439510239],
                    length=0.52,
                    width=1.15,
                    height=0.10,
                ),
                step(
                    "stair_step_2",
                    2.15,
                    0.0,
                    0.18,
                    [0.02, 0.08],
                    [0.05, 0.20],
                    [2.09439510239, 4.18879020479],
                    length=0.52,
                    width=1.15,
                    height=0.18,
                ),
                step(
                    "stair_step_3",
                    2.75,
                    0.0,
                    0.26,
                    [0.02, 0.09],
                    [0.06, 0.22],
                    [4.18879020479, 6.28318530718],
                    length=0.58,
                    width=1.15,
                    height=0.26,
                ),
            ],
        ),
        course_layout(
            "offset_staircase",
            "hard",
            0.95,
            1.25,
            0.72,
            [
                step(
                    "offset_stair_left_1",
                    1.45,
                    -0.24,
                    0.12,
                    [0.02, 0.08],
                    [0.05, 0.22],
                    [0.0, 2.09439510239],
                    length=0.56,
                    width=0.78,
                    height=0.12,
                ),
                step(
                    "offset_stair_right_2",
                    2.15,
                    0.24,
                    0.20,
                    [0.02, 0.10],
                    [0.05, 0.25],
                    [2.09439510239, 4.18879020479],
                    length=0.58,
                    width=0.78,
                    height=0.20,
                ),
                step(
                    "offset_stair_left_3",
                    2.85,
                    -0.18,
                    0.28,
                    [0.02, 0.09],
                    [0.06, 0.24],
                    [4.18879020479, 6.28318530718],
                    length=0.60,
                    width=0.82,
                    height=0.28,
                ),
            ],
        ),
        course_layout(
            "increasing_platform_sequence",
            "hardest",
            0.9,
            1.3,
            0.70,
            [
                step(
                    "platform_entry_step",
                    1.45,
                    0.0,
                    0.12,
                    [0.02, 0.08],
                    [0.08, 0.22],
                    [0.0, 2.09439510239],
                    length=0.55,
                    width=1.15,
                    height=0.12,
                ),
                step(
                    "platform_mid_step",
                    2.15,
                    0.0,
                    0.22,
                    [0.02, 0.09],
                    [0.06, 0.22],
                    [2.09439510239, 4.18879020479],
                    length=0.75,
                    width=1.15,
                    height=0.22,
                ),
                step(
                    "platform_exit_step",
                    3.00,
                    0.0,
                    0.30,
                    [0.03, 0.10],
                    [0.08, 0.25],
                    [4.18879020479, 6.28318530718],
                    length=0.78,
                    width=1.15,
                    height=0.30,
                ),
            ],
        ),
    ],
    "pure_gap": [
        course_layout(
            "short_platform_gap",
            "easy",
            1.0,
            1.2,
            0.65,
            [
                gap(
                    "short_platform_gap",
                    2.2,
                    0.0,
                    0.10,
                    "x",
                    [0.05, 0.18],
                    [0.05, 0.20],
                    [0.0, 6.28318530718],
                    separation=1.15,
                    length=0.58,
                    width=1.15,
                    height=0.10,
                ),
            ],
        ),
        course_layout(
            "medium_platform_gap",
            "medium",
            1.0,
            1.25,
            0.68,
            [
                gap(
                    "medium_platform_gap",
                    2.35,
                    0.0,
                    0.10,
                    "x",
                    [0.04, 0.14],
                    [0.05, 0.18],
                    [0.0, 6.28318530718],
                    separation=1.35,
                    length=0.60,
                    width=1.20,
                    height=0.10,
                ),
            ],
        ),
        course_layout(
            "wide_platform_gap",
            "hard",
            1.0,
            1.35,
            0.70,
            [
                gap(
                    "wide_platform_gap",
                    2.55,
                    0.0,
                    0.10,
                    "x",
                    [0.05, 0.15],
                    [0.04, 0.16],
                    [0.0, 6.28318530718],
                    separation=1.60,
                    length=0.80,
                    width=1.20,
                    height=0.10,
                ),
            ],
        ),
        course_layout(
            "repeated_staggered_gaps",
            "hardest",
            0.9,
            1.3,
            0.72,
            [
                gap(
                    "double_gap_entry",
                    1.55,
                    -0.22,
                    0.10,
                    "x",
                    [0.04, 0.12],
                    [0.05, 0.18],
                    [0.0, 3.14159265359],
                    separation=1.05,
                    length=0.52,
                    width=0.95,
                    height=0.10,
                ),
                gap(
                    "double_gap_exit",
                    3.05,
                    0.22,
                    0.10,
                    "x",
                    [0.04, 0.12],
                    [0.05, 0.22],
                    [3.14159265359, 6.28318530718],
                    separation=1.15,
                    length=0.55,
                    width=0.95,
                    height=0.10,
                ),
            ],
        ),
    ],
    "pure_ramp": [
        course_layout(
            "soft_ramp_course",
            "easy",
            1.0,
            1.2,
            0.65,
            [
                ramp(
                    "ramp_soft",
                    2.0,
                    0.0,
                    0.12,
                    [0.03, 0.10],
                    [0.05, 0.18],
                    [0.0, 6.28318530718],
                    base_pitch=0.10,
                    length=1.35,
                    width=1.15,
                    thickness=0.045,
                ),
            ],
        ),
        course_layout(
            "steep_ramp_course",
            "medium",
            0.95,
            1.25,
            0.65,
            [
                ramp(
                    "ramp_steep",
                    2.4,
                    0.0,
                    0.14,
                    [0.06, 0.18],
                    [0.08, 0.25],
                    [0.0, 6.28318530718],
                    base_pitch=0.18,
                    length=1.55,
                    width=1.15,
                    thickness=0.045,
                ),
            ],
        ),
        course_layout(
            "reverse_down_ramp_course",
            "hard",
            0.95,
            1.25,
            0.65,
            [
                ramp(
                    "ramp_reverse",
                    2.3,
                    0.0,
                    0.12,
                    [0.04, 0.14],
                    [0.05, 0.20],
                    [0.0, 6.28318530718],
                    base_pitch=-0.10,
                    length=1.50,
                    width=1.15,
                    thickness=0.045,
                ),
            ],
        ),
        course_layout(
            "tilted_ramp_pair_course",
            "hardest",
            0.9,
            1.35,
            0.72,
            [
                ramp(
                    "ramp_pair_up",
                    1.75,
                    -0.18,
                    0.12,
                    [0.03, 0.12],
                    [0.06, 0.20],
                    [0.0, 3.14159265359],
                    base_pitch=0.12,
                    length=1.25,
                    width=1.10,
                    thickness=0.045,
                ),
                ramp(
                    "ramp_pair_down",
                    3.05,
                    0.18,
                    0.12,
                    [0.04, 0.14],
                    [0.06, 0.22],
                    [3.14159265359, 6.28318530718],
                    base_pitch=-0.08,
                    length=1.25,
                    width=1.10,
                    thickness=0.045,
                ),
            ],
        ),
    ],
    "mixed": [
        course_layout(
            "hurdle_step_ramp_course",
            "medium",
            0.95,
            1.25,
            0.70,
            [
                hurdle(
                    "mixed_hurdle_entry",
                    1.25,
                    0.0,
                    0.31,
                    "y",
                    [0.07, 0.18],
                    [0.08, 0.24],
                    [0.0, 6.28318530718],
                    length=0.10,
                    thickness=1.10,
                    height=0.31,
                ),
                step(
                    "mixed_step_mid",
                    2.30,
                    0.0,
                    0.18,
                    [0.02, 0.08],
                    [0.06, 0.20],
                    [0.0, 6.28318530718],
                    length=0.62,
                    width=1.10,
                    height=0.18,
                ),
                ramp(
                    "mixed_ramp_exit",
                    3.55,
                    0.0,
                    0.12,
                    [0.03, 0.12],
                    [0.06, 0.22],
                    [0.0, 6.28318530718],
                    base_pitch=0.10,
                    length=1.30,
                    width=1.10,
                    thickness=0.045,
                ),
            ],
        ),
        course_layout(
            "gap_landing_step_ramp_course",
            "hard",
            0.95,
            1.3,
            0.70,
            [
                gap(
                    "course_takeoff_gap",
                    1.60,
                    0.0,
                    0.10,
                    "x",
                    [0.04, 0.12],
                    [0.05, 0.18],
                    [0.0, 6.28318530718],
                    separation=1.05,
                    length=0.52,
                    width=1.10,
                    height=0.10,
                ),
                step(
                    "course_landing_step",
                    2.95,
                    0.0,
                    0.20,
                    [0.02, 0.09],
                    [0.06, 0.22],
                    [0.0, 6.28318530718],
                    length=0.60,
                    width=1.10,
                ),
                ramp(
                    "course_exit_ramp",
                    4.20,
                    0.0,
                    0.12,
                    [0.04, 0.14],
                    [0.06, 0.22],
                    [0.0, 6.28318530718],
                    base_pitch=0.12,
                    length=1.30,
                    width=1.10,
                    thickness=0.045,
                ),
            ],
        ),
        course_layout(
            "hurdle_gap_staircase_ramp_course",
            "hardest",
            0.9,
            1.35,
            0.74,
            [
                hurdle(
                    "full_course_hurdle",
                    1.10,
                    0.0,
                    0.32,
                    "y",
                    [0.06, 0.18],
                    [0.08, 0.24],
                    [0.0, 6.28318530718],
                    length=0.10,
                    thickness=1.05,
                    height=0.30,
                ),
                gap(
                    "full_course_gap",
                    2.25,
                    0.0,
                    0.10,
                    "x",
                    [0.04, 0.14],
                    [0.05, 0.18],
                    [0.0, 6.28318530718],
                    separation=1.05,
                    length=0.50,
                    width=1.08,
                    height=0.10,
                ),
                step(
                    "full_course_stair_1",
                    3.25,
                    -0.16,
                    0.14,
                    [0.02, 0.09],
                    [0.06, 0.22],
                    [0.0, 3.14159265359],
                    length=0.52,
                    width=0.82,
                    height=0.14,
                ),
                step(
                    "full_course_stair_2",
                    3.85,
                    0.16,
                    0.24,
                    [0.02, 0.09],
                    [0.06, 0.22],
                    [3.14159265359, 6.28318530718],
                    length=0.56,
                    width=0.82,
                    height=0.24,
                ),
                ramp(
                    "full_course_ramp",
                    5.05,
                    0.0,
                    0.12,
                    [0.03, 0.12],
                    [0.05, 0.20],
                    [0.0, 6.28318530718],
                    base_pitch=0.10,
                    length=1.30,
                    width=1.08,
                    thickness=0.045,
                ),
            ],
        ),
    ],
}


def suite_names():
    return tuple(DYNAMIC_TERRAIN_SUITES.keys())


def get_suite_layouts(suite):
    if suite not in DYNAMIC_TERRAIN_SUITES:
        raise ValueError(
            "Unknown dynamic terrain suite '{}'. Supported suites are {}.".format(
                suite, suite_names()
            )
        )
    return DYNAMIC_TERRAIN_SUITES[suite]


def layout_actor_count(layout):
    return sum(obstacle["actor_count"] for obstacle in layout["obstacles"])


def max_suite_actor_count(suite):
    return max(layout_actor_count(layout) for layout in get_suite_layouts(suite))
