#!/usr/bin/env python3
"""Generate top-down atlas images for original Extreme Parkour terrains.

This script mirrors the output style of `utils/plot_dynamic_terrain_layouts.py`:
- one PNG per terrain cell,
- one overview image,
- one contact sheet,
- one README index,
- red ordered goal markers,
- dashed route line,
- black robot-start marker.

It visualizes the heightfield generated by `legged_gym/utils/terrain.py`.
It does not create an Isaac Gym simulation, does not run PPO, and does not open
an Isaac Gym viewer window.
"""

from isaacgym import gymapi, gymtorch, gymutil  # must be imported before torch

import argparse
from copy import deepcopy
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

import legged_gym.envs  # registers tasks
from legged_gym.utils.task_registry import task_registry
from legged_gym.utils.terrain import Terrain


ROOT = Path(__file__).resolve().parents[1]


def get_attr(obj, name, default=None):
    return getattr(obj, name, default)


def score_goal_candidate(goals_xy, terrain_length, terrain_width):
    """Score whether goals look like local cell coordinates."""

    if goals_xy is None or len(goals_xy) == 0:
        return -1.0

    goals_xy = np.asarray(goals_xy, dtype=np.float32)
    x = goals_xy[:, 0]
    y = goals_xy[:, 1]

    # Allow a margin because original goals can be slightly outside the exact
    # visible obstacle area.
    inside = (
        (x >= -0.5)
        & (x <= terrain_length + 0.5)
        & (y >= -terrain_width / 2.0 - 0.5)
        & (y <= terrain_width / 2.0 + 0.5)
    )
    return float(np.mean(inside))


def to_local_goals(raw_goals, row, col, terrain, terrain_cfg):
    """Convert original terrain goals to local cell coordinates.

    Different versions of the Extreme Parkour terrain code may store goals as
    already-local coordinates, global map coordinates, or coordinates relative
    to env origins. This function tries several plausible transforms and keeps
    the one that best fits the local plot extent.
    """

    if raw_goals is None:
        return None

    goals = np.asarray(raw_goals, dtype=np.float32)
    if goals.ndim != 2 or goals.shape[1] < 2:
        return None

    terrain_length = float(terrain_cfg.terrain_length)
    terrain_width = float(terrain_cfg.terrain_width)

    goals_xy = goals[:, :2].copy()
    candidates = []

    # Candidate 0: already local, y centered around 0.
    candidates.append(goals_xy.copy())

    # Candidate 1: global map coords with cell origin at row/col start.
    c = goals_xy.copy()
    c[:, 0] -= row * terrain_length
    c[:, 1] -= col * terrain_width + terrain_width / 2.0
    candidates.append(c)

    # Candidate 2: global map coords with y already centered per cell.
    c = goals_xy.copy()
    c[:, 0] -= row * terrain_length
    c[:, 1] -= col * terrain_width
    candidates.append(c)

    # Candidate 3: world coords relative to env origin if available.
    env_origins = getattr(terrain, "env_origins", None)
    if env_origins is not None:
        try:
            origin_xy = np.asarray(env_origins[row, col, :2], dtype=np.float32)
            c = goals_xy.copy()
            # Keep x in a local forward coordinate and y in lateral coordinates.
            c[:, 0] = c[:, 0] - origin_xy[0] + terrain_length / 2.0
            c[:, 1] = c[:, 1] - origin_xy[1]
            candidates.append(c)
        except Exception:
            pass

    return max(
        candidates,
        key=lambda arr: score_goal_candidate(arr, terrain_length, terrain_width),
    )


def crop_cell(height, row, col, border_px, length_px, width_px):
    x0 = border_px + row * length_px
    y0 = border_px + col * width_px
    return height[x0 : x0 + length_px, y0 : y0 + width_px]


def draw_goals(ax, goals):
    if goals is None:
        return

    goals = np.asarray(goals, dtype=np.float32)
    if goals.ndim != 2 or goals.shape[1] < 2 or len(goals) == 0:
        return

    goal_x = goals[:, 0]
    goal_y = goals[:, 1]

    ax.plot(goal_x, goal_y, linestyle="--", linewidth=1.0, color="red", alpha=0.8)
    ax.scatter(goal_x, goal_y, marker="o", s=32, color="red", zorder=10)

    for goal_id, (x, y) in enumerate(zip(goal_x, goal_y)):
        ax.text(
            float(x) + 0.04,
            float(y) + 0.04,
            str(goal_id),
            fontsize=7,
            color="red",
            zorder=11,
        )


def plot_cell(
    ax,
    crop,
    terrain_cfg,
    title,
    goals=None,
    show_labels=True,
    show_colorbar=False,
):
    """Draw one original static terrain cell using dynamic-atlas style."""

    terrain_length = float(terrain_cfg.terrain_length)
    terrain_width = float(terrain_cfg.terrain_width)

    extent = [
        0.0,
        terrain_length,
        -terrain_width / 2.0,
        terrain_width / 2.0,
    ]

    im = ax.imshow(
        crop.T,
        origin="lower",
        extent=extent,
        aspect="auto",
        cmap="terrain",
    )

    # Match the dynamic atlas convention.
    ax.scatter([0.0], [0.0], marker="o", s=60, color="black", zorder=8)
    ax.plot(
        [0.0, terrain_length],
        [0.0, 0.0],
        linestyle="--",
        linewidth=1,
        color="gray",
        alpha=0.75,
    )
    draw_goals(ax, goals)

    ax.set_title(title, fontsize=9)
    ax.set_xlim(0.0, terrain_length)
    ax.set_ylim(-terrain_width / 2.0, terrain_width / 2.0)
    ax.set_aspect("auto")
    ax.grid(True, alpha=0.25)

    if show_labels:
        ax.set_xlabel("x: forward direction")
        ax.set_ylabel("y: lateral direction")
    else:
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.tick_params(labelsize=6)

    if show_colorbar:
        return im

    return None


def plot_overview(
    height, terrain, terrain_cfg, rows, cols, border_px, length_px, width_px, out_path
):
    """Draw raw overview with cell grid, similar to the original script."""

    fig, ax = plt.subplots(figsize=(12, 10))
    ax.imshow(height.T, origin="lower", cmap="terrain", aspect="auto")
    ax.set_title(
        f"Original terrain overview: rows={rows}, cols={cols}",
        fontsize=13,
    )
    ax.set_xlabel("x pixels")
    ax.set_ylabel("y pixels")

    for r in range(rows + 1):
        x = border_px + r * length_px
        ax.axvline(x, color="black", linewidth=0.5, alpha=0.5)
    for c in range(cols + 1):
        y = border_px + c * width_px
        ax.axhline(y, color="black", linewidth=0.5, alpha=0.5)

    fig.tight_layout()
    fig.savefig(out_path, dpi=180)
    plt.close(fig)


def write_markdown_index(out_dir, task, rows, cols, image_paths):
    md_path = out_dir / "README.md"
    lines = [
        "# Original Terrain Atlas",
        "",
        "This atlas is generated from the original static Extreme Parkour terrain pipeline.",
        "It is a top-down design preview, not an Isaac Gym render.",
        "",
        f"Task: `{task}`",
        f"Rows: `{rows}`",
        f"Cols: `{cols}`",
        "",
        "Visual convention:",
        "",
        "- Height colors: original heightfield values",
        "- Black dot: nominal robot start",
        "- Gray dashed line: nominal forward route centerline",
        "- Red dots: original terrain goals / waypoints",
        "- Red dashed line: ordered goal path",
        "",
        "## Overview",
        "",
        "![overview](overview.png)",
        "",
        "## Contact Sheet",
        "",
        "![contact sheet](contact_sheet.png)",
        "",
        "## Cells",
        "",
    ]

    for row, col, img in image_paths:
        lines.append(f"### row={row}, col={col}")
        lines.append("")
        lines.append(f"![row {row} col {col}]({img})")
        lines.append("")

    md_path.write_text("\n".join(lines), encoding="utf-8")
    return md_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", default="a1", help="Task name, e.g. a1 or go1.")
    parser.add_argument("--rows", type=int, default=6)
    parser.add_argument("--cols", type=int, default=6)
    parser.add_argument(
        "--out_dir",
        default="utils/original_terrain_atlas",
        help="Output directory for generated PNGs and README.md.",
    )
    parser.add_argument(
        "--max_cells",
        type=int,
        default=None,
        help="Optional limit for quick debugging.",
    )
    args = parser.parse_args()

    out_dir = ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    env_cfg, _ = task_registry.get_cfgs(name=args.task)
    terrain_cfg = deepcopy(env_cfg.terrain)
    terrain_cfg.num_rows = args.rows
    terrain_cfg.num_cols = args.cols

    num_envs = args.rows * args.cols
    terrain = Terrain(terrain_cfg, num_envs)

    height_raw = np.asarray(terrain.height_field_raw)
    height = height_raw.astype(np.float32) * float(terrain_cfg.vertical_scale)

    border_px = int(
        get_attr(
            terrain,
            "border",
            terrain_cfg.border_size / terrain_cfg.horizontal_scale,
        )
    )
    length_px = int(
        get_attr(
            terrain,
            "length_per_env_pixels",
            terrain_cfg.terrain_length / terrain_cfg.horizontal_scale,
        )
    )
    width_px = int(
        get_attr(
            terrain,
            "width_per_env_pixels",
            terrain_cfg.terrain_width / terrain_cfg.horizontal_scale,
        )
    )

    print("Generated original terrain heightfield")
    print(f"height shape: {height.shape}")
    print(f"rows={args.rows}, cols={args.cols}")
    print(f"border_px={border_px}, length_px={length_px}, width_px={width_px}")
    print(f"out_dir={out_dir}")

    overview_path = out_dir / "overview.png"
    plot_overview(
        height,
        terrain,
        terrain_cfg,
        args.rows,
        args.cols,
        border_px,
        length_px,
        width_px,
        overview_path,
    )

    raw_goals = getattr(terrain, "goals", None)
    image_paths = []
    cell_records = []

    cell_count = 0
    for row in range(args.rows):
        for col in range(args.cols):
            if args.max_cells is not None and cell_count >= args.max_cells:
                break

            crop = crop_cell(height, row, col, border_px, length_px, width_px)

            cell_goals = None
            if raw_goals is not None:
                try:
                    cell_goals = to_local_goals(
                        raw_goals[row, col],
                        row=row,
                        col=col,
                        terrain=terrain,
                        terrain_cfg=terrain_cfg,
                    )
                except Exception:
                    cell_goals = None

            fig, ax = plt.subplots(figsize=(8, 4.5))
            title = f"original / row {row}, col {col}"
            im = plot_cell(
                ax,
                crop,
                terrain_cfg,
                title,
                goals=cell_goals,
                show_labels=True,
                show_colorbar=True,
            )
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="height")
            fig.tight_layout()

            img_path = out_dir / f"cell_r{row}_c{col}.png"
            fig.savefig(img_path, dpi=180)
            plt.close(fig)

            image_paths.append((row, col, img_path.name))
            cell_records.append((row, col, crop, cell_goals))
            cell_count += 1

        if args.max_cells is not None and cell_count >= args.max_cells:
            break

    # Contact sheet: this is the key piece that matches the dynamic atlas review flow.
    fig, axes = plt.subplots(
        args.rows,
        args.cols,
        figsize=(args.cols * 3.2, args.rows * 1.8),
        squeeze=False,
    )
    record_map = {
        (row, col): (crop, cell_goals) for row, col, crop, cell_goals in cell_records
    }

    for row in range(args.rows):
        for col in range(args.cols):
            ax = axes[row][col]
            record = record_map.get((row, col))
            if record is None:
                ax.axis("off")
                continue

            crop, cell_goals = record
            plot_cell(
                ax,
                crop,
                terrain_cfg,
                title=f"r{row} c{col}",
                goals=cell_goals,
                show_labels=False,
                show_colorbar=False,
            )

    fig.suptitle(f"Original terrain contact sheet: task={args.task}", fontsize=14)
    fig.tight_layout()
    contact_sheet_path = out_dir / "contact_sheet.png"
    fig.savefig(contact_sheet_path, dpi=180)
    plt.close(fig)

    md_path = write_markdown_index(
        out_dir=out_dir,
        task=args.task,
        rows=args.rows,
        cols=args.cols,
        image_paths=image_paths,
    )

    print(f"Wrote {overview_path}")
    print(f"Wrote {contact_sheet_path}")
    print(f"Wrote {md_path}")
    print("Done.")


if __name__ == "__main__":
    main()
